version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  default_labels:
      - "automerge"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  default_labels:
      - "automerge"